
#
# This is 1 of ZAWA's 10 habitat ranges. Each sub-range has its own list of biomes, and all of the sub-range's entities will spawn in those biomes.
# Disable entities (or a species variant) by setting "enabled" under their category to false.
# Use ONLY whole numbers greater than 0 for chance, min, and max!
# "chance" is how common they spawn, a higher number is more common than a lower number. "min" and "max" adjusts their spawning group size.
# !! If modded biomes are not generated, delete the entire "biomes" line for each sub-category and restart minecraft. !!
#
#
[dry_forest]
	biomes = ["minecraft:savanna_plateau", "minecraft:shattered_savanna_plateau", "genericeco:baobab_plateau", "genericeco:canyon_plateau", "genericeco:lush_savanna_plateau", "genericeco:marula_plateau", "minecraft:forest", "minecraft:wooded_hills", "minecraft:birch_forest", "minecraft:birch_forest_hills", "minecraft:flower_forest", "genericeco:alder_forest", "genericeco:alder_forest_hills", "genericeco:ash_forest", "genericeco:ash_forest_hills", "genericeco:basswood_forest", "genericeco:basswood_forest_hills", "genericeco:beech_woods", "genericeco:beech_wooded_hills", "genericeco:butternut_woods", "genericeco:butternut_wooded_hills", "genericeco:cherry_blossom_forest", "genericeco:cherry_blossom_hills", "genericeco:chestnut_forest", "genericeco:chestnut_grove", "genericeco:cypress_grove", "genericeco:cypress_hills", "genericeco:dense_forest", "genericeco:dense_wooded_hills", "genericeco:dogwood_forest", "genericeco:dogwood_forest_hills", "genericeco:dying_forest", "genericeco:dying_wooded_hills", "genericeco:elm_forest", "genericeco:elm_forest_hills", "genericeco:fungal_woodland", "genericeco:fungal_wooded_hills", "genericeco:ginkgo_woods", "genericeco:ginkgo_clearing", "genericeco:grove", "genericeco:grove_hills", "genericeco:hazel_woods", "genericeco:hazel_hills", "genericeco:hickory_woodland", "genericeco:hickory_wooded_hills", "genericeco:hornbeam_forest", "genericeco:hornbeam_hills", "genericeco:jacaranda_grove", "genericeco:jacaranda_hills", "genericeco:japanese_maple_forest", "genericeco:japanese_maple_hills", "genericeco:lavender_meadow", "genericeco:linden_forest", "genericeco:linden_forest_hills", "genericeco:magnolia_grove", "genericeco:magnolia_hills", "genericeco:maple_forest", "genericeco:maple_forest_hills", "genericeco:mystical_valley", "genericeco:mystical_fields", "genericeco:oak_woodland", "genericeco:oak_wooded_hills", "genericeco:orchard", "genericeco:plane_forest", "genericeco:plane_forest_hills", "genericeco:poplar_grove", "genericeco:poplar_hills", "genericeco:wooded_prairie", "genericeco:robinia_woodland", "genericeco:robinia_wooded_hills", "genericeco:walnut_forest", "genericeco:walnut_hills", "genericeco:wisteria_forest", "genericeco:wisteria_hills", "genericeco:zelkova_forest", "genericeco:zelkova_hills", "otg:ssaow.birch_forest", "otg:ssaow.tall_birch_forest", "otg:ssaow.wooded_hills", "otg:ssaow.birch_forest_hills", "otg:ssaow.tall_birch_hills", "otg:ssaow.flower_forest", "otg:ssaow.forest", "otg:default.birch_forest", "otg:default.tall_birch_forest", "otg:default.wooded_hills", "otg:default.birch_forest_hills", "otg:default.tall_birch_hills", "otg:default.flower_forest", "otg:default.forest", "twilightforest:forest", "twilightforest:firefly_forest", "twilightforest:oak_savannah", "twilightforest:mushroom_forest", "twilightforest:dense_mushroom_forest", "twilightforest:enchanted_forest", "gaiadimension:pink_agate_forest", "gaiadimension:mutant_agate_wildwood", "gaiadimension:shining_grove"]

	[dry_forest.military_macaw]
		chance = 10
		min = 1
		max = 4
		enabled = true

	[dry_forest.koala]
		chance = 10
		min = 1
		max = 1
		enabled = true

	[dry_forest.blue_throated_macaw]
		chance = 10
		min = 1
		max = 4
		enabled = true

	[dry_forest.spix_macaw]
		chance = 10
		min = 1
		max = 4
		enabled = true

[temperate_forest]
	biomes = ["minecraft:forest", "minecraft:wooded_hills", "minecraft:birch_forest", "minecraft:birch_forest_hills", "minecraft:wooded_mountains", "minecraft:flower_forest", "genericeco:alder_forest", "genericeco:alder_forest_hills", "genericeco:appalachian_mountains", "genericeco:ash_forest", "genericeco:ash_forest_hills", "genericeco:balsa_forest", "genericeco:balsa_forest_hills", "genericeco:basswood_forest", "genericeco:basswood_forest_hills", "genericeco:beech_woods", "genericeco:beech_wooded_hills", "genericeco:butternut_woods", "genericeco:butternut_wooded_hills", "genericeco:cherry_blossom_forest", "genericeco:cherry_blossom_hills", "genericeco:chestnut_forest", "genericeco:chestnut_grove", "genericeco:cypress_grove", "genericeco:cypress_hills", "genericeco:dense_forest", "genericeco:dense_wooded_hills", "genericeco:dogwood_forest", "genericeco:dogwood_forest_hills", "genericeco:dying_forest", "genericeco:dying_wooded_hills", "genericeco:elm_forest", "genericeco:elm_forest_hills", "genericeco:fungal_woodland", "genericeco:fungal_wooded_hills", "genericeco:ginkgo_woods", "genericeco:ginkgo_clearing", "genericeco:grove", "genericeco:grove_hills", "genericeco:hazel_woods", "genericeco:hazel_hills", "genericeco:hickory_woodland", "genericeco:hickory_wooded_hills", "genericeco:hornbeam_forest", "genericeco:hornbeam_hills", "genericeco:jacaranda_grove", "genericeco:jacaranda_hills", "genericeco:japanese_maple_forest", "genericeco:japanese_maple_hills", "genericeco:lavender_meadow", "genericeco:linden_forest", "genericeco:linden_forest_hills", "genericeco:magnolia_grove", "genericeco:magnolia_hills", "genericeco:maple_forest", "genericeco:maple_forest_hills", "genericeco:mystical_valley", "genericeco:mystical_fields", "genericeco:oak_woodland", "genericeco:oak_wooded_hills", "genericeco:orchard", "genericeco:plane_forest", "genericeco:plane_forest_hills", "genericeco:poplar_grove", "genericeco:poplar_hills", "genericeco:wooded_prairie", "genericeco:robinia_woodland", "genericeco:robinia_wooded_hills", "genericeco:walnut_forest", "genericeco:walnut_hills", "genericeco:wisteria_forest", "genericeco:wisteria_hills", "genericeco:zelkova_forest", "genericeco:zelkova_hills", "otg:ssaow.birch_forest", "otg:ssaow.tall_birch_forest", "otg:ssaow.wooded_hills", "otg:ssaow.birch_forest_hills", "otg:ssaow.wooded_mountains", "otg:ssaow.tall_birch_hills", "otg:ssaow.flower_forest", "otg:ssaow.gravelly_mountains_", "otg:ssaow.forest", "otg:default.birch_forest", "otg:default.tall_birch_forest", "otg:default.wooded_hills", "otg:default.birch_forest_hills", "otg:default.wooded_mountains", "otg:default.tall_birch_hills", "otg:default.flower_forest", "otg:default.gravelly_mountains_", "otg:default.forest", "twilightforest:forest", "twilightforest:firefly_forest", "twilightforest:oak_savannah", "twilightforest:mushroom_forest", "twilightforest:dense_mushroom_forest", "twilightforest:enchanted_forest", "projectvibrantjourneys:flooded_woodlands", "gaiadimension:pink_agate_forest", "gaiadimension:mutant_agate_wildwood", "gaiadimension:shining_grove", "minecraft:bamboo_jungle", "minecraft:bamboo_jungle_hills"]

	[temperate_forest.chinese_praying_mantis]
		chance = 4
		min = 1
		max = 1
		enabled = true

	[temperate_forest.honey_bee]
		chance = 10
		min = 3
		max = 5
		enabled = true

	[temperate_forest.butterfly]
		chance = 10
		min = 1
		max = 4
		enabled = true

	[temperate_forest.european_praying_mantis]
		chance = 4
		min = 1
		max = 1
		enabled = true

[wet_forest]
	biomes = ["minecraft:dark_forest", "minecraft:dark_forest_hills", "genericeco:sinister_forest", "otg:ssaow.dark_forest_hills", "otg:ssaow.dark_forest", "otg:default.dark_forest_hills", "otg:default.dark_forest", "vampirism:vampire_forest", "twilightforest:spooky_forest", "twilightforest:dark_forest", "twilightforest:dark_forest_center", "genericeco:temperate_rainforest", "genericeco:temperate_rainforest_hills", "twilightforest:firefly_forest", "gaiadimension:mutant_agate_wildwood", "gaiadimension:shining_grove", "genericeco:balsa_forest", "genericeco:balsa_forest_hills", "genericeco:temperate_rainforest", "genericeco:temperate_rainforest_hills", "genericeco:wetland_forest", "projectvibrantjourneys:flooded_woodlands"]

	[wet_forest.kakapo]
		chance = 5
		min = 1
		max = 2
		enabled = true

	[wet_forest.brown_rat]
		chance = 15
		min = 2
		max = 4
		enabled = true

