
#
# This is 1 of ZAWA's 10 habitat ranges. Each sub-range has its own list of biomes, and all of the sub-range's entities will spawn in those biomes.
# Disable entities (or a species variant) by setting "enabled" under their category to false.
# Use ONLY whole numbers greater than 0 for chance, min, and max!
# "chance" is how common they spawn, a higher number is more common than a lower number. "min" and "max" adjusts their spawning group size.
# !! If modded biomes are not generated, delete the entire "biomes" line for each sub-category and restart minecraft. !!
#
#
[dry_rainforest]
	biomes = ["minecraft:plains", "minecraft:sunflower_plains", "genericeco:bushland", "genericeco:bushland_hills", "genericeco:flowering_fields", "genericeco:grassland", "genericeco:tall_grassland", "genericeco:lavender_fields", "genericeco:lavender_meadow", "genericeco:marsh", "genericeco:dense_marsh", "genericeco:meadow", "genericeco:meadow_forest", "genericeco:moor", "genericeco:moor_lowlands", "genericeco:prairie", "genericeco:pasture", "genericeco:wooded_prairie", "genericeco:shrubland", "genericeco:dense_shrubland", "genericeco:steppe", "genericeco:steppe_uplands", "otg:ssaow.plains", "otg:ssaow.sunflower_plains", "otg:default.plains", "otg:default.sunflower_plains", "projectvibrantjourneys:pine_meadows", "projectvibrantjourneys:prairie", "projectvibrantjourneys:blossoming_fields", "projectvibrantjourneys:meadows", "projectvibrantjourneys:stony_fields", "gaiadimension:goldstone_lands", "gaiadimension:crystal_plains", "minecraft:jungle_edge", "minecraft:modified_jungle_edge", "minecraft:bamboo_jungle", "minecraft:bamboo_jungle_hills", "genericeco:bamboo_forest", "genericeco:bamboo_hills", "genericeco:eucalyptus_forest", "genericeco:eucalyptus_hills", "genericeco:kapok_jungle", "genericeco:kapok_jungle_hills", "genericeco:overgrown_cliffs", "genericeco:overgrown_flats", "genericeco:rainbow_eucalyptus_forest", "genericeco:rainbow_eucalyptus_hills", "genericeco:rainforest", "genericeco:rainforest_hills", "genericeco:rainforest_basin", "genericeco:rosewood_forest", "genericeco:rosewood_forest_hills", "genericeco:sacred_springs", "genericeco:tropical_rainforest", "genericeco:tropical_rainforest_hills", "genericeco:tropical_rainforest_basin", "otg:ssaow.jungle_edge", "otg:default.jungle_edge", "gaiadimension:green_agate_jungle"]

	[dry_rainforest.mexican_red_knee_tarantula]
		chance = 4
		min = 1
		max = 1
		enabled = true

	[dry_rainforest.red_shouldered_macaw]
		chance = 10
		min = 1
		max = 4
		enabled = true

	[dry_rainforest.ghost_praying_mantis]
		chance = 4
		min = 1
		max = 1
		enabled = true

	[dry_rainforest.hyacinth_macaw]
		chance = 10
		min = 1
		max = 4
		enabled = true

	[dry_rainforest.antilles_pinktoe_tarantula]
		chance = 4
		min = 1
		max = 1
		enabled = true

[wet_rainforest]
	biomes = ["minecraft:jungle", "minecraft:jungle_hills", "minecraft:modified_jungle", "genericeco:ebony_forest", "genericeco:ebony_forest_hills", "genericeco:mahogany_forest", "genericeco:mahogany_clearing", "genericeco:temperate_rainforest", "genericeco:temperate_rainforest_hills", "otg:ssaow.bamboo_jungle_hills", "otg:ssaow.jungle_hills", "otg:ssaow.jungle", "otg:ssaow.modified_jungle_edge", "otg:ssaow.modified_jungle", "otg:ssaow.bamboo_jungle", "otg:default.bamboo_jungle_hills", "otg:default.jungle_hills", "otg:default.jungle", "otg:default.modified_jungle_edge", "otg:default.modified_jungle", "otg:default.bamboo_jungle", "projectvibrantjourneys:overgrown_spires", "minecraft:swamp", "minecraft:swamp_hills", "genericeco:bayou", "genericeco:bayou_glade", "genericeco:dark_swampland", "genericeco:dark_swampland_hills", "genericeco:dark_swampland_marshes", "genericeco:dying_swamp", "genericeco:dying_swamp_hills", "genericeco:lush_swamp", "genericeco:lush_swamp_hills", "genericeco:lush_swamp_marshes", "genericeco:mangrove", "genericeco:mire", "genericeco:wooded_mire", "genericeco:moor", "genericeco:moor_lowlands", "genericeco:muskeg", "genericeco:snowy_muskeg", "genericeco:swamp_marshes", "otg:ssaow.swamp", "otg:ssaow.swamp_hills", "otg:default.swamp", "otg:default.swamp_hills", "twilightforest:swamp", "twilightforest:fire_swamp", "projectvibrantjourneys:mangrove_marsh", "projectvibrantjourneys:willow_wetlands", "gaiadimension:purple_agate_swamp"]

	[wet_rainforest.green_winged_macaw]
		chance = 10
		min = 1
		max = 4
		enabled = true

	[wet_rainforest.brown_spider_monkey]
		chance = 10
		min = 3
		max = 3
		enabled = true

	[wet_rainforest.wrinkled_hornbill]
		chance = 10
		min = 2
		max = 3
		enabled = true

	[wet_rainforest.goliath_birdeater_tarantula]
		chance = 4
		min = 1
		max = 1
		enabled = true

	[wet_rainforest.blue_and_gold_macaw]
		chance = 10
		min = 1
		max = 4
		enabled = true

	[wet_rainforest.corydoras]
		chance = 10
		min = 4
		max = 5
		enabled = true

	[wet_rainforest.scarlet_macaw]
		chance = 10
		min = 1
		max = 4
		enabled = true

	[wet_rainforest.wreathed_hornbill]
		chance = 10
		min = 2
		max = 3
		enabled = true

	[wet_rainforest.chestnut_fronted_macaw]
		chance = 10
		min = 1
		max = 4
		enabled = true

	[wet_rainforest.cobalt_blue_tarantula]
		chance = 4
		min = 1
		max = 1
		enabled = true

[deep_rainforest]
	biomes = ["minecraft:jungle", "minecraft:jungle_hills", "minecraft:modified_jungle", "minecraft:modified_jungle_edge", "minecraft:bamboo_jungle", "minecraft:bamboo_jungle_hills", "genericeco:bamboo_forest", "genericeco:bamboo_hills", "genericeco:ebony_forest", "genericeco:ebony_forest_hills", "genericeco:eucalyptus_forest", "genericeco:eucalyptus_hills", "genericeco:kapok_jungle", "genericeco:kapok_jungle_hills", "genericeco:mahogany_forest", "genericeco:mahogany_clearing", "genericeco:overgrown_cliffs", "genericeco:overgrown_flats", "genericeco:rainbow_eucalyptus_forest", "genericeco:rainbow_eucalyptus_hills", "genericeco:rainforest", "genericeco:rainforest_hills", "genericeco:rainforest_basin", "genericeco:rosewood_forest", "genericeco:rosewood_forest_hills", "genericeco:sacred_springs", "genericeco:tropical_rainforest", "genericeco:tropical_rainforest_hills", "genericeco:tropical_rainforest_basin", "otg:ssaow.bamboo_jungle_hills", "otg:ssaow.jungle_hills", "otg:ssaow.jungle", "otg:ssaow.modified_jungle_edge", "otg:ssaow.modified_jungle", "otg:ssaow.bamboo_jungle", "otg:default.bamboo_jungle_hills", "otg:default.jungle_hills", "otg:default.jungle", "otg:default.modified_jungle_edge", "otg:default.modified_jungle", "otg:default.bamboo_jungle", "projectvibrantjourneys:overgrown_spires", "gaiadimension:green_agate_jungle"]

	[deep_rainforest.asian_forest_scorpion]
		chance = 4
		min = 1
		max = 1
		enabled = true

	[deep_rainforest.orchid_praying_mantis]
		chance = 4
		min = 1
		max = 1
		enabled = true

	[deep_rainforest.emperor_scorpion]
		chance = 4
		min = 1
		max = 1
		enabled = true

	[deep_rainforest.butterfly]
		chance = 10
		min = 1
		max = 4
		enabled = true

	[deep_rainforest.palawan_hornbill]
		chance = 10
		min = 2
		max = 3
		enabled = true

	[deep_rainforest.rhinoceros_hornbill]
		chance = 10
		min = 2
		max = 3
		enabled = true

	[deep_rainforest.sumatran_orangutan]
		chance = 8
		min = 1
		max = 1
		enabled = true

	[deep_rainforest.red_claw_scorpion]
		chance = 4
		min = 1
		max = 1
		enabled = true

	[deep_rainforest.black_headed_spider_monkey]
		chance = 10
		min = 3
		max = 3
		enabled = true

	[deep_rainforest.red_faced_spider_monkey]
		chance = 10
		min = 3
		max = 3
		enabled = true

