
#----------------------------------------|| Food settings ||----------------------------------------
[food_properties]

	[food_properties.grape]
		#Range: 0.1 ~ 3.0
		grapeSaturation = 0.2
		#Range: 1 ~ 20
		grapeHunger = 4

	[food_properties.mulberry]
		#Range: 1 ~ 20
		mulberryHunger = 1
		#Range: 0.1 ~ 3.0
		mulberrySaturation = 0.5

	[food_properties.maize]
		#Range: 1 ~ 20
		maizeHunger = 6
		#Range: 0.1 ~ 3.0
		maizeSaturation = 1.0

#----------------------------------------|| Armor settings ||---------------------------------------
[armor_properties]

	[armor_properties.holy]
		#Feet damage reduction :
		#Range: 1 ~ 100
		holyDefenseFeet = 5
		#This armor's enchantability :
		#Range: 1 ~ 100
		holyEnchantability = 8
		#Chest damage reduction :
		#Range: 1 ~ 100
		holyDefenseChest = 10
		#Legs damage reduction :
		#Range: 1 ~ 100
		holyDefenseLegs = 8
		#This armor's toughness :
		#Range: 0.0 ~ 100.0
		holyToughness = 4.0
		#DurabilityFactor is multiplied with a value that depends on the armor part (between 11 and 16) to get the total durability :
		#Range: 1 ~ 1000
		holyDurabilityFactor = 45
		#Helmet damage reduction :
		#Range: 1 ~ 100
		holyDefenseHelmet = 5

	[armor_properties.raijin]
		#Legs damage reduction :
		#Range: 1 ~ 100
		raijinDefenseLegs = 8
		#Feet damage reduction :
		#Range: 1 ~ 100
		raijinDefenseFeet = 4
		#Helmet damage reduction :
		#Range: 1 ~ 100
		raijinDefenseHelmet = 4
		#This armor's enchantability :
		#Range: 1 ~ 100
		raijinEnchantability = 26
		#This armor's toughness :
		#Range: 0.0 ~ 100.0
		raijinToughness = 2.0
		#DurabilityFactor is multiplied with a value that depends on the armor part (between 11 and 16) to get the total durability :
		#Range: 1 ~ 1000
		raijinDurabilityFactor = 45
		#Chest damage reduction :
		#Range: 1 ~ 100
		raijinDefenseChest = 10

	[armor_properties.o_yoroi]
		#Feet damage reduction :
		#Range: 1 ~ 100
		oYoroiDefenseFeet = 3
		#Helmet damage reduction :
		#Range: 1 ~ 100
		oYoroiDefenseHelmet = 3
		#This armor's enchantability :
		#Range: 1 ~ 100
		oYoroiEnchantability = 10
		#Chest damage reduction :
		#Range: 1 ~ 100
		oYoroiDefenseChest = 8
		#This armor's toughness :
		#Range: 0.0 ~ 100.0
		oYoroiToughness = 2.0
		#Legs damage reduction :
		#Range: 1 ~ 100
		oYoroiDefenseLegs = 6
		#DurabilityFactor is multiplied with a value that depends on the armor part (between 11 and 16) to get the total durability :
		#Range: 1 ~ 1000
		oYoroiDurabilityFactor = 33

	[armor_properties.japanese_light]
		#Feet damage reduction :
		#Range: 1 ~ 100
		japaneseLightDefenseFeet = 1
		#Helmet damage reduction :
		#Range: 1 ~ 100
		japaneseLightDefenseHelmet = 2
		#This armor's toughness :
		#Range: 0.0 ~ 100.0
		japaneseLightToughness = 0.0
		#Legs damage reduction :
		#Range: 1 ~ 100
		japaneseLightDefenseLegs = 5
		#This armor's enchantability :
		#Range: 1 ~ 100
		japaneseLightEnchantability = 14
		#DurabilityFactor is multiplied with a value that depends on the armor part (between 11 and 16) to get the total durability :
		#Range: 1 ~ 1000
		japaneseLightDurabilityFactor = 15
		#Chest damage reduction :
		#Range: 1 ~ 100
		japaneseLightDefenseChest = 6

	[armor_properties.iron_plate]
		#Legs damage reduction :
		#Range: 1 ~ 100
		ironPlateDefenseLegs = 5
		#Feet damage reduction :
		#Range: 1 ~ 100
		ironPlateDefenseFeet = 2
		#Helmet damage reduction :
		#Range: 1 ~ 100
		ironPlateDefenseHelmet = 2
		#This armor's toughness :
		#Range: 0.0 ~ 100.0
		ironPlateToughness = 0.0
		#This armor's enchantability :
		#Range: 1 ~ 100
		ironPlateEnchantability = 20
		#Chest damage reduction :
		#Range: 1 ~ 100
		ironPlateDefenseChest = 6
		#DurabilityFactor is multiplied with a value that depends on the armor part (between 11 and 16) to get the total durability :
		#Range: 1 ~ 1000
		ironPlateDurabilityFactor = 15

	[armor_properties.pharaoh]
		#Legs damage reduction :
		#Range: 1 ~ 100
		pharaohDefenseLegs = 6
		#This armor's toughness :
		#Range: 0.0 ~ 100.0
		pharaohToughness = 0.0
		#DurabilityFactor is multiplied with a value that depends on the armor part (between 11 and 16) to get the total durability :
		#Range: 1 ~ 1000
		pharaohDurabilityFactor = 12
		#This armor's enchantability :
		#Range: 1 ~ 100
		pharaohEnchantability = 37
		#Chest damage reduction :
		#Range: 1 ~ 100
		pharaohDefenseChest = 8
		#Feet damage reduction :
		#Range: 1 ~ 100
		pharaohDefenseFeet = 3
		#Helmet damage reduction :
		#Range: 1 ~ 100
		pharaohDefenseHelmet = 3

#---------------------------------------|| Entity settings ||---------------------------------------
[entity_properties]

	[entity_properties.japanese_dragon]
		japanese_dragon_mute = false
		#Range: 1 ~ 100
		japanese_dragon_default_attack = 4
		#Range: 1 ~ 10000
		japanese_dragon_default_max_health = 60

	[entity_properties.silkmoth]
		#The probability to change the rotation point each tick is equal to 1/x, with x the following value :
		#Range: 10 ~ 10000
		silkmoth_rotation_change = 400
		silkmoth_dies_after_one_day = true
		silkmoth_mute = false
		#Range: 0 ~ 10
		silkmoth_rotation_max_range = 2
		#The probability to spawn a Silkmoth on a Mulberry each random tick is equal to 1/x, with x the following value :
		#Range: 10 ~ 10000
		climbingPlantGrowthChance = 400

#---------------------------------------|| Block settings ||----------------------------------------
[block_properties]

	[block_properties.stick_bundle]
		#Worms have a probability to grow on random tick equal to 1/x, with x the following value :
		#Range: 1 ~ 1000
		stickBundleGrowthChance = 25

	[block_properties.climbing_plant]
		#The probability to grow is equal to 1/x, with x the following value :
		#Range: 1 ~ 200
		climbingPlantGrowthChance = 16
		#If the plant could have grown (see climbingPlantGrowthChance), it has a probability to spread to an adjacent block equal to 1/x, with x the following value :
		#Range: 1 ~ 1000
		climbingPlantSpreadChance = 5

	[block_properties.dryer]
		#The drying time of an item is randomly set in an interval around the default time from the recipe. The following value defines the high bound of the interval in percents. IE, if you choose '20', the interval will be [ 83.3% , 120%]. If you chose '200', the interval will be [33.3% , 300%] :
		#Range: 0 ~ 100000
		dryingTimeVariationRange = 30

#----------------------------------|| World generation settings ||----------------------------------
[world_generation]

	[world_generation.wild_grape]
		#For each spawn zone, a position will be chose x times to place this plant, with x the following value :
		#Range: 1 ~ 200
		wildGrapeRolls = 64
		#List of biomes where this plant should spawn during world generation (must be empty if the plant must not spawn :
		wildGrapeBiomes = []

	[world_generation.wild_maize]
		#For each spawn zone, a position will be chose x times to place this plant, with x the following value :
		#Range: 1 ~ 200
		wildMaizeRolls = 64
		#List of biomes where this plant should spawn during world generation (must be empty if the plant must not spawn :
		wildMaizeBiomes = []

	[world_generation.mulberry]
		#For each spawn zone, a position will be chose x times to place this plant, with x the following value :
		#Range: 1 ~ 200
		mulberryRolls = 64

	[world_generation.commelina]
		#For each spawn zone, a position will be chose x times to place this plant, with x the following value :
		#Range: 1 ~ 200
		commelinaRolls = 64

	[world_generation.rice]
		#For each spawn zone, a position will be chose x times to place this plant, with x the following value :
		#Range: 1 ~ 200
		riceRolls = 64
		#List of biomes where this plant should spawn during world generation (must be empty if the plant must not spawn :
		riceBiomes = []

	[world_generation.camellia]
		#For each spawn zone, a position will be chose x times to place this plant, with x the following value :
		#Range: 1 ~ 200
		camelliaRolls = 5
		#List of biomes where this plant should spawn during world generation (must be empty if the plant must not spawn :
		camelliaBiomes = ["minecraft:flower_forest", "minecraft:jungle", "minecraft:jungle_hills", "minecraft:jungle_edge"]

	[world_generation.cypress]
		#For each spawn zone, a position will be chose x times to place this plant, with x the following value :
		#Range: 1 ~ 200
		cypressRolls = 15

