
[fatigue]
	#Fatigue is decreased by this number while you sleep (every tick)
	fatigueReplenishRate = 0.00833
	#The required amount of fatigue to sleep
	minimumFatigueToSleep = 20
	#Definitions of fatigue replenishing items. Each list consist of an item registry name, the amount of fatigue it replenishes, and optionally a fatigue rate modifier
	replenishingItems = [["coffeespawner:coffee", 10], ["coffeespawner:coffee_milk", 10], ["coffeespawner:coffee_sugar", 15], ["coffeespawner:coffee_milk_sugar", 15], ["coffeemod:coffee", 15], ["coffeemod:espresso", 15], ["coffeemod:latte", 15], ["coffeemod:caramel_macchiato", 10], ["coffeemod:mocha", 10], ["coffeemod:frappe", 10]]
	#Fatigue is incremented by this number every tick
	fatigueRate = 0.00208
	#Definitions of each side effect stage in order: min fatigue, max fatigue, potion ID, duration, amplifier. For a permanent effect, set the duration to -1.
	sideEffectStages = [[70, 80, 9, 150, 0], [80, 90, 2, 300, 2], [90, 95, 19, 200, 1], [95, 100, 2, -1, 3]]
	#Enables fatigue side effects
	fatigueSideEffects = true

[logic]
	#Maximum tick speed multiplier, activated during sleep
	multiplierCap = 100.0
	#If the time difference (mc) between multiplied ticking is greater than this, the simulation multiplier is lowered. Otherwise, it's increased. Lowering this number might slow down simulation and improve performance. Don't mess around with it if you don't know what you're doing.
	#Range: 1.0 ~ 50.0
	delta = 50.0
	#Minimum tick speed multiplier, activated during sleep
	baseMultiplier = 1.0

[options]
	#the item used to select wake time
	wakeTimeSelectItem = "minecraft:clock"
	#Allows you to sleep with armor equipped
	sleepWithArmor = false
	#Let the player sleep even when there are monsters nearby
	ignoreMonsters = false
	#Deafens you while you're asleep. Mob sounds are confusing with the world sped up
	muteSoundWhenSleeping = false
	#Slightly slower sleep start/end
	fading = true

[performance]
	#Disables mob spawning while you sleep
	disableCreatureSpawning = false

[timings]
	#Specifies the start of the valid sleep period
	#Range: 0 ~ 24000
	validSleepStart = 0
	#Specifies the end of the period in which the player can enter sleep
	#Range: 0 ~ 24000
	enterSleepEnd = 24000
	#Specifies the start of the period in which the player can enter sleep
	#Range: 0 ~ 24000
	enterSleepStart = 0
	#Specifies the end of the valid sleep period
	#Range: 0 ~ 24000
	validSleepEnd = 24000

