
#General settings
[general]
	#Mana & Artifice level cost for Ars Nouveau
	#Range: > 0
	mana_artifice_level_cost = 5
	#Intelligence Level cost for PlayerEx (Magic Damage (magic damage*(1.0f + this))) 
	#Range: 0.0 ~ 1.7976931348623157E308
	xp_level_cost = 0.02
	#Intelligence Level cost for PlayerEx (Mana & Artifice)
	#Range: 0.0 ~ 1.7976931348623157E308
	xp_level_cost_mna = 0.05
	#Intelligence Level cost for PlayerEx (Ars Nouveau)
	#Range: 0.0 ~ 1.7976931348623157E308
	xp_level_cost_ars = 0.05

