#Show the config menu button in the Options menu
"Enable In-Game Config" = true
#Overrides all other config options for easy difficulty management
#This value is changed by the in-game config. It does nothing otherwise.
#Range: 1 ~ 5
Difficulty = 3

["Item settings"]
	#Ice Resistance blocks all cold temperatures
	"Ice Resistance Immunity" = true
	#Fire Resistance blocks all hot temperatures
	"Fire Resistance Immunity" = true
	#Thermometer item is required to see world temperature
	"Require Thermometer" = true

["Misc things that are affected by temperature"]
	#Sets whether damage scales with difficulty
	"Damage Scaling" = true

["Details about how the player is affected by temperature"]
	#Rate at which the player's body temperature changes (default: 1.0 (100%))
	#Range: 0.0 ~ Infinity
	"Rate Multiplier" = 1.0
	#Minimum habitable temperature (default: 0.42857142857142855)
	#Range: -Infinity ~ Infinity
	"Minimum Habitable Temperature" = 0.42857142857142855
	#Maximum habitable temperature (default: 1.619047619047619)
	#Range: -Infinity ~ Infinity
	"Maximum Habitable Temperature" = 1.619047619047619

["Grace Period Details"]
	#Enables the grace period (default: true)
	"Grace Period Enabled" = true
	#Grace period length in ticks (default: 6000)
	#Range: > 0
	"Grace Period Length" = 6000

["Block Effects"]
	#Allows for adding simple BlockTemps without the use of Java mods
	#Format (All temperatures are in Minecraft units):
	#[["block-ids", <temperature>, <range (max 7)>, <*true/false: weaken over distance>, <*max effect>], [etc...], [etc...]]
	#(* = optional) (1 °MC = 42 °F/ 23.33 °C)
	#
	#Arguments:
	#block-ids: multiple IDs can be used by separating them with commas (i.e: "minecraft:torch,minecraft:wall_torch")
	#temperature: the temperature of the block, in Minecraft units
	#weaken over distance: the block is less effective as distance increases
	#max effect: the max temperature change this block can cause to a player (even with multiple blocks)
	BlockTemps = [["minecraft:soul_fire", -0.2, 7, true, 0.8], ["minecraft:fire", 0.2, 7, true, 0.8], ["minecraft:magma_block", 0.15, 3, true, 0.6], ["minecraft:ice", -0.2, 1.5, true, 0.8], ["minecraft:packed_ice", -0.3, 1.5, true, 1.2], ["minecraft:blue_ice", -0.4, 1.5, true, 1.6]]

["Hearth Strength"]
	#How strong the hearth is (default: 0.5)
	#Range: 0.0 ~ 1.0
	"Hearth Strength" = 0.5

["Cold Soul Fire"]
	#Converts damage dealt by Soul Fire to cold damage (default: true)
	#Does not affect the block's temperature
	"Cold Soul Fire" = true

