
[dimension]
	#Set which dimensions are blacklisted or whitelisted for affected undead
	dimensions = []
	#Set whether the dimension configuration is blacklisted or whitelisted
	#Allowed Values: BLACKLIST, WHITELIST
	dimensionPermission = "BLACKLIST"

[holy]
	#The amount of time, in seconds, that smiting from fire lasts
	#Range: 0 ~ 100
	fireSmiteDuration = 10
	#The amount of time, in seconds, that smiting from holy sources lasts
	#Range: 0 ~ 100
	holySmiteDuration = 10
	#A list of entities that will be able to damage and smite undead
	holyEntities = []
	#A list of potion effects that will be able to damage and smite undead
	holyEffects = ["minecraft:instant_health", "consecration:holy"]
	#A list of items that will be able to damage and smite undead
	holyItems = []
	#A list of enchantments that will be able to damage and smite undead
	holyEnchantments = ["minecraft:smite"]
	#A list of damage types that will be able to damage and smite undead
	holyDamage = ["holy"]
	#A list of materials that will be able to damage and smite undead
	holyMaterial = ["silver"]

[undying]
	#Set to true to give default undead the undying trait
	defaultUndead = true
	#A list of mobs that to classify as undead.
	#Format: 'modid:name'
	#Optionally, add ';unholy' or ';absolute' to the end.
	#Unholy mobs will not be smote by fire and absolute mobs will not be smote by anything.
	undeadList = []
	#Set undead natural damage reduction, in percent, against all non-holy damage
	#Range: 0.0 ~ 1.0
	damageReduction = 0.8
	#Set undead natural health regen, in half-hearts per second
	#Range: 0 ~ 1000
	healthRegen = 1
	#Set undead natural bonus speed modifier
	#Range: 0.0 ~ 100.0
	speedModifier = 0.0
	#Set to true to have undead reduce damage against non-player non-holy entities
	bystanderNerf = true

