
[morph]
	#Time (in ticks) for a morph to complete.
	#Range: > 1
	morphTime = 100
	#Morph normally only recalculates size when it has to. This makes Morph recalculate the player size every tick whilst morphed.
	aggressiveSizeRecalculation = false
	#Which attributes are supported by more, and how are values better. Format: <Resource Name of Attribute>;<more/less>. EG: "minecraft:generic.max_health;more".
	supportedAttributes = ["minecraft:generic.max_health;more;20", "minecraft:generic.knockback_resistance;more", "minecraft:generic.movement_speed;more;0.1", "minecraft:generic.attack_damage;more", "minecraft:generic.attack_knockback;more", "minecraft:generic.attack_speed;more", "minecraft:generic.armor;more", "minecraft:generic.luck;more", "minecraft:horse.jump_strength;more", "forge:swim_speed;more", "forge:reach_distance;more"]
	#ID of traits you want to disable.
	disabledTraits = []
	#Set the morph entity instance to silent, this disables ambient noise and any sound the morph makes.
	silentMorphs = false

[biomass]
	#How much of the entity volume is considered their mass.
	#Range: 0.0 ~ 1.7976931348623157E308
	biomassValue = 0.3
	#Enable the Biomass ability without requiring the advancement to unlock it?
	biomassBypassAdvancement = false

#These options affect the gameplay while using the mod.
[gameplay]
	#Resource Location name for Mob types you cannot acquire biomass or morphs from.
	disabledMobs = ["minecraft:armor_stand"]
	#The mode the mod runs in. Accepts CLASSIC, DISGUISE. DEFAULT has been disabled until it has been finished.
	#Allowed Values: DEFAULT, CLASSIC, DISGUISE
	morphMode = "CLASSIC"
	#The Biomass Skin is meant to show during invisibility. Turning this off disables that.
	biomassSkinWhilstInvisible = true

